version: '3.9'

volumes:
  # html:
  dbfilewc:

networks:
  app:
    driver: bridge

services:

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: docker-phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 300
      POST_MAX_SIZE: 1024M
      UPLOAD_MAX_FILESIZE: 1024M
    depends_on:
      - db
    networks:
      - app


  db:
    image: mysql:8.0
    container_name: docker-db
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wp_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - dbfilewc:/var/lib/mysql
      - ./configuration/db/mysql/my.cnf:/etc/my.cnf #for shrink RAM
    networks:
      - app

  server:
    container_name: docker-server
    build:
      context: ./configuration/server
    volumes:
      - ./html/:/var/www/html/
      # - ./html/wp-content/plugins:/var/www/html/wp-content/plugins
      # - ./html/wp-content/themes/storefront:/var/www/html/wp-content/themes/storefront
      # - ./html/wp-content/uploads:/var/www/html/wp-content/uploads

      - ./configuration/server/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./html/wp-config.php:/var/www/html/wp-config.php


      # - ./html/wp-content/wp-includes:/var/www/html/wp-content/wp-includes
      # - ./html/.htaccess:/var/www/html/.htaccess


    env_file:
      ./html/.env
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - app