version: '3.9'

volumes:
  # html:
  dbfilewc:

networks:
  app:
    driver: bridge

services:

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: docker-phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 300
      POST_MAX_SIZE: 1024M
      UPLOAD_MAX_FILESIZE: 1024M
    depends_on:
      - db
    networks:
      - app


  db:
    image: mysql:8.0
    container_name: docker-db
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wp_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - dbfilewc:/var/lib/mysql
      - ./configuration/db/mysql/my.cnf:/etc/my.cnf #for shrink RAM
    networks:
      - app

  server:
    container_name: docker-server
    build:
      context: ./configuration/server
    volumes:
      - ./html/:/var/www/html/
      - ./configuration/server/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

      - ./vendor/:/var/www/vendor/
      # - ./phpcs.xml:/var/www/phpcs.xml
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    env_file:
      ./html/.env
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - app